### llama
POST https://intelligent-mirage-message.glitch.me/llama
Content-Type: application/json

{
    "prompt":"오늘 저녁 메뉴를 추천해줘"
}

### deepseek
POST https://intelligent-mirage-message.glitch.me/deepseek
Content-Type: application/json

{
  "prompt":"오늘 저녁 메뉴를 추천해줘"
}